### PR TITLE
Gaia 8000

### PR DESCRIPTION
**Pull request by zmanian**
Update for gaia-8000

* [x] Duplicated new genesis file in `latest` directory

### CODE REVIEW

**Comment by zmanian** [comment]
it's state dump from gaia-7005 taken this morning.

**Comment by cwgoes** [comment]
Hmm have we tried this? I can't find e.g. governance deposit procedure in state, I think it might not be exported correctly - https://github.com/cosmos/cosmos-sdk/blob/develop/cmd/gaia/app/app.go#L196.

**Comment by cwgoes** [comment]
Here's a PR to fix - https://github.com/cosmos/cosmos-sdk/pull/2098 - but if we want to change the bond denomination for gaia-8000 we'll need to backport that fix into the release.

**Comment by ValarDragon** [comment]
I think we should switch back to steak. It didn't seem like we reached consensus in the issue that we want testnet-atoms as the token.

**Pull request merged**
