### PR TITLE
merge v6-vega testnet repo to testnet repo

### PR DESCRIPTION
**Pull request by yaruwangway**
* [ ] Duplicated new genesis file in `latest` directory

### CODE REVIEW

**Comment by uditvira** [comment]
What are we doing with the current cosmos/vega-test repo? Should we be providing an archival notice? Does this have implications on any communication/marketing materials that currently have links to the vega-test repo?

**Comment by uditvira** [comment]
@nooomski mentioned the following need to be updated in the hub docs:

* readme.md
* docs/hub-tutorials/join-testnet.md
* docs/migration/cosmoshub-4-vega-upgrade.md

@yaruwangway can you confirm the naming convention moving fwd? is it `v6-vega` or `v6-Vega`?

**Comment by nooomski** [comment]
@uditvira that's `v6-Vega` as per https://github.com/cosmos/gaia/issues/902#issuecomment-1054454894

**Comment by yaruwangway** [comment]
> What are we doing with the current cosmos/vega-test repo? Should we be providing an archival notice? Does this have implications on any communication/marketing materials that currently have links to the vega-test repo?

good point, I think maybe 

> @nooomski mentioned the following need to be updated in the hub docs:
> 
> * readme.md
> * docs/hub-tutorials/join-testnet.md
> * docs/migration/cosmoshub-4-vega-upgrade.md
> 
> @yaruwangway can you confirm the naming convention moving fwd? is it `v6-vega` or `v6-Vega`?

it is `v6-Vega`, but this name convention only starts from `v7-Theta`, because our vega updrade already used `Vega` as upgrade name.
here is the discussion: https://github.com/cosmos/gaia/issues/902

**Review by uditvira — APPROVED** [review]

**Pull request merged**
